name: Deploy Blazor PWA to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build --baseurl "/BlazorPawAgentX"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
